=== luisulisesquinteros-ux/DAM-LMSGI-LuisUlisesQuinterosQuinteros/Entrega 4/Exercici01/1.4/XSDcifp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <!-- Tipos simples -->
  <xs:simpleType name="cursType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DAM"/>
      <xs:enumeration value="DAW"/>
      <xs:enumeration value="ASIX"/>
      <xs:enumeration value="SMX"/>
      <xs:enumeration value="SEIA"/>
      <xs:enumeration value="ER"/>
      <xs:enumeration value="AUT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="departamentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Informàtica"/>
      <xs:enumeration value="Electricitat"/>
      <xs:enumeration value="Automoció"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Element raíz -->
  <xs:element name="cifp">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumne" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="llinatges" type="xs:string"/>
              <xs:element name="data_naixement" type="xs:string" minOccurs="0"/>
              <xs:element name="correu" type="xs:string" minOccurs="0"/>
              <xs:element name="telefon" type="xs:string" minOccurs="0"/>
              <xs:element name="adreça" type="xs:string" minOccurs="0"/>
              <xs:element name="data_matricula" type="xs:string"/>
              <xs:element name="curs">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="valor" type="cursType" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="professor" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom" type="xs:string"/>
              <xs:element name="llinatges" type="xs:string"/>
              <xs:element name="data_naixement" type="xs:string" minOccurs="0"/>
              <xs:element name="correu" type="xs:string" minOccurs="0"/>
              <xs:element name="telefon" type="xs:string" minOccurs="0"/>
              <xs:element name="adreça" type="xs:string" minOccurs="0"/>
              <xs:element name="data_incorporacio" type="xs:string"/>
              <xs:element name="departament">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="valor" type="departamentType" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <xs:element name="assignatura" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom_assignatura">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="cicle" type="cursType" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="data_inici" type="xs:string" minOccurs="0"/>
                    <xs:element name="data_final" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="id_assignatura" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== luisulisesquinteros-ux/DAM-LMSGI-LuisUlisesQuinterosQuinteros/Entrega 4/Exercici01/1.4/cifpXsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<cifp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="XSDcifp.xsd">
  <alumne id="1">
    <nom>Luis Ulises</nom>
    <llinatges>Quinteros Quinteros</llinatges>
    <data_matricula>2026-02-08</data_matricula>
    <curs valor="DAM">DAM</curs>
  </alumne>

  <professor id="10">
    <nom>Benito</nom>
    <llinatges>Perez Galdós</llinatges>
    <data_incorporacio>2020-01-10</data_incorporacio>
    <departament valor="Informàtica">Informàtica</departament>

    <assignatura id_assignatura="11">
      <nom_assignatura cicle="DAM">Programacio</nom_assignatura>
      <data_inici>2026-01-08</data_inici>
    </assignatura>
  </professor>
</cifp>
